---
title: "Logo A-B Test"
author: "Simon Bond"
date: "`r Sys.Date()`"
output: html_document
---



# Eudract R Package

This is a package with the aim 

 * tools that will prepare the required statistics needed by EudraCT or ClinicalTrials.gov and format them into the precise requirements to directly upload an XML file into the web portal, with no further data entry by hand.
 * It also outputs standard frequency tables and dot-plot figures for standard safety reporting
 
 * [Eudract Home Page](https://eudract-tool.medschl.cam.ac.uk/)
 * [CRAN Package](https://cran.r-project.org/web/packages/eudract/index.html)
 
# R package verse
 
 It has recently been accepted into the Pharmaverse suite of validated packages, as it can now also accept input data
 in the ADaM/CDISC format
 
 [Pharmaverse](https://pharmaverse.org/e2eclinical/tlg/)
 
 
 It suggest that we need a logo to represent the package . 
 
 


# Logo A/B Test - Instructions

You will be shown a series of pairs of logos. For each pair, please select the logo you think is
better. The process works like a knock-out tournament.

### Step 1 - Launch the Shiny app in R

* Open R (Or Rstudio)
* Run the following command:
`shiny::runApp("~/STATISTICS/NON STUDY FOLDER/Academic Research/Eudract Tool/logo")`

### Step 2 - Complete the A/B Choices

* The app will display two logos at a time.
* Click the radio button to say which logo you prefer. Hit "Submit" to move to the next pair
* Continue until all pairs are completed

### Step 3 - Download and save your results

* When finished, click the "Download" button
* Save the downloaded file with your name/initials in the filename
* Save it into the folder
`STATISTICS/NON STUDY FOLDER/Academic Research/Eudract Tool/logo/results`
